/**
 * The price moves the news must explain: for every company its biggest months, and for every
 * month the market's move and the biggest movers. Written to data/news/arcs/movers.md for the
 * people (and agents) who write the story arcs. Run after `npm run data:build`.
 */
import fs from "node:fs";
import path from "node:path";
import { OUT_DIR, DATA_DIR } from "./lib/paths.js";
import type { AssetSeries } from "./lib/asset.js";
import { nameAt } from "@marketsim/shared";

const GAME_START = "1979-12";
const assets: AssetSeries[] = fs.readdirSync(OUT_DIR).filter((f) => f.endsWith(".json")).map((f) => JSON.parse(fs.readFileSync(path.join(OUT_DIR, f), "utf8")));
const stocks = assets.filter((a) => a.kind === "stock").sort((a, b) => a.id.localeCompare(b.id));
const gold = assets.find((a) => a.id === "gold")!;
const sp: { rows: { month: string; price: number }[] } = JSON.parse(fs.readFileSync(path.join(DATA_DIR, "reference", "sp500.json"), "utf8"));

const pct = (x: number) => `${x >= 0 ? "+" : ""}${(x * 100).toFixed(0)}%`;
const listedMonth = (s: AssetSeries) => (s.listed && s.listed > s.rows[0].month ? s.listed : s.rows[0].month);

interface Move { month: string; change: number }
function moves(rows: { month: string; price: number }[], from = GAME_START): Move[] {
  const out: Move[] = [];
  for (let i = 1; i < rows.length; i++) if (rows[i].month >= from) out.push({ month: rows[i].month, change: rows[i].price / rows[i - 1].price - 1 });
  return out;
}

const lines: string[] = [];
lines.push("# Price moves the news must explain", "",
  "Generated by `npm run movers -w data` from data/out and data/reference/sp500.json. Monthly changes of month-end prices in USD",
  "(dividends excluded). Every move listed here should be explained by a beat in an arc, or noted there as having no identifiable cause.", "");

// --- the market ---
const spMoves = moves(sp.rows);
const years = new Map<string, number>();
const dec = new Map(sp.rows.filter((r) => r.month.endsWith("-12")).map((r) => [r.month.slice(0, 4), r.price]));
for (const [y, p] of dec) { const prev = dec.get(String(Number(y) - 1)); if (prev) years.set(y, p / prev - 1); }
lines.push("## The market: S&P 500", "", "Biggest months:", "");
for (const m of [...spMoves].sort((a, b) => Math.abs(b.change) - Math.abs(a.change)).slice(0, 25).sort((a, b) => a.month.localeCompare(b.month))) lines.push(`- ${m.month}: ${pct(m.change)}`);
lines.push("", "Calendar years (December to December):", "");
for (const [y, c] of years) if (y >= "1980") lines.push(`- ${y}: ${pct(c)}`);
lines.push("", "Gold, biggest months:", "");
for (const m of [...moves(gold.rows)].sort((a, b) => Math.abs(b.change) - Math.abs(a.change)).slice(0, 12).sort((a, b) => a.month.localeCompare(b.month))) lines.push(`- ${m.month}: ${pct(m.change)}`);
lines.push("");

// --- per company ---
lines.push("## Companies: the biggest months of each", "");
for (const s of stocks) {
  const ms = moves(s.rows, listedMonth(s));
  if (!ms.length) continue;
  const first = s.rows.find((r) => r.month >= listedMonth(s))!;
  const last = s.rows[s.rows.length - 1];
  const total = last.price / first.price - 1;
  const years = (s.rows.length - s.rows.indexOf(first)) / 12;
  const top = [...ms].sort((a, b) => Math.abs(b.change) - Math.abs(a.change)).slice(0, 12).sort((a, b) => a.month.localeCompare(b.month));
  // worst and best stretches: peak-to-trough drawdown and the strongest 12 months
  let peak = first.price, peakMonth = first.month, dd = 0, ddFrom = "", ddTo = "";
  for (const r of s.rows) {
    if (r.month < listedMonth(s)) continue;
    if (r.price > peak) { peak = r.price; peakMonth = r.month; }
    const d = r.price / peak - 1;
    if (d < dd) { dd = d; ddFrom = peakMonth; ddTo = r.month; }
  }
  let best = { from: "", to: "", change: -1 };
  const rows = s.rows.filter((r) => r.month >= listedMonth(s));
  for (let i = 12; i < rows.length; i++) { const c = rows[i].price / rows[i - 12].price - 1; if (c > best.change) best = { from: rows[i - 12].month, to: rows[i].month, change: c }; }
  const names = [s.name, ...(s.renames ?? []).map((r) => r.name)].join(" / ");
  lines.push(`### ${s.id}: ${names}`, "",
    `In the game ${listedMonth(s)} to ${last.month}${s.end ? ` (${s.end.type}: ${s.end.note})` : ""}; price ${first.price} to ${last.price} (${pct(total)} over ${years.toFixed(1)} years).`,
    `Worst stretch: ${pct(dd)} from ${ddFrom} to ${ddTo}. Best twelve months: ${pct(best.change)} from ${best.from} to ${best.to}.`, "",
    "Biggest months:", "");
  for (const m of top) {
    const idx = spMoves.find((x) => x.month === m.month);
    lines.push(`- ${m.month}: ${pct(m.change)}${idx ? ` (market ${pct(idx.change)})` : ""}`);
  }
  lines.push("");
}

// --- per month ---
lines.push("## Month by month: the market and the biggest movers", "",
  "Market = S&P 500. Movers = the three largest moves among the companies in the game that month, when at least 10% or clearly against the market.", "");
const byMonth = new Map<string, { id: string; name: string; change: number }[]>();
for (const s of stocks) for (const m of moves(s.rows, listedMonth(s))) {
  const list = byMonth.get(m.month) ?? [];
  list.push({ id: s.id, name: nameAt(s, m.month), change: m.change });
  byMonth.set(m.month, list);
}
let year = "";
for (const m of spMoves) {
  if (m.month.slice(0, 4) !== year) { year = m.month.slice(0, 4); lines.push(`### ${year}`, ""); }
  const movers = (byMonth.get(m.month) ?? [])
    .filter((x) => Math.abs(x.change) >= 0.1 || Math.abs(x.change - m.change) >= 0.12)
    .sort((a, b) => Math.abs(b.change) - Math.abs(a.change)).slice(0, 3);
  lines.push(`- ${m.month}: market ${pct(m.change)}${movers.length ? "; " + movers.map((x) => `${x.name} ${pct(x.change)}`).join(", ") : ""}`);
}
lines.push("");

const outDir = path.join(DATA_DIR, "news", "arcs");
fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, "movers.md"), lines.join("\n"));
console.log(`wrote ${path.relative(DATA_DIR, path.join(outDir, "movers.md"))}: ${stocks.length} companies, ${spMoves.length} months`);
